"""Add branding table for white-label

Revision ID: 799fd757127e
Revises: 52e54f835a07
Create Date: 2026-08-16 12:59:32.291252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '799fd757127e'
down_revision: Union[str, None] = '52e54f835a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branding')
    # ### end Alembic commands ###
