"""Add memberships, target retention, scan status, result judge_reason

Revision ID: a31bbdafd5e3
Revises: d560784b731d
Create Date: 2026-08-16 12:17:31.530907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31bbdafd5e3'
down_revision: Union[str, None] = 'd560784b731d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    op.add_column('results', sa.Column('judge_reason', sa.Text(), nullable=True))
    op.add_column('scans', sa.Column('status', sa.String(length=50), nullable=False, server_default='done'))
    op.add_column('targets', sa.Column('retention', sa.String(length=50), nullable=False, server_default='delete_after_scan'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'retention')
    op.drop_column('scans', 'status')
    op.drop_column('results', 'judge_reason')
    op.drop_table('memberships')
    # ### end Alembic commands ###
