"""Add library_version to scans table

Revision ID: b5f8b56f3812
Revises: be2494f1af40
Create Date: 2026-08-16 01:17:46.910911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f8b56f3812'
down_revision: Union[str, None] = 'be2494f1af40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('library_version', sa.String(length=50), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'library_version')
    # ### end Alembic commands ###
