"""Add token and expires_at to ownership_verifications

Revision ID: d560784b731d
Revises: b5f8b56f3812
Create Date: 2026-08-16 12:07:50.563807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd560784b731d'
down_revision: Union[str, None] = 'b5f8b56f3812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ownership_verifications', sa.Column('token', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('ownership_verifications', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ownership_verifications', 'expires_at')
    op.drop_column('ownership_verifications', 'token')
    # ### end Alembic commands ###
